name: Tests

on: 
  push:
    branches: [main]

jobs: 
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node dependencies
      run: npm install
    - name: Run tests
      run: npm run test:unit
    - name: Build the app
      run: npm run build
    - name: Delete dist folder
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{ github.workspace }}/dist

        
