name: Tests

on: 
  push:
    branches: [main]

jobs: 
  setup: 
    name: Installing Dependencies
    runs-on: ubuntu-latest
    steps: 
      - name: Install Node
        run: npm install
  # test:
  #   name: Unit Testing
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install Node
  #     run: npm run test:unit
